import { DEPLOYMENT_ENV } from './deploymentEnv';

const productionConfig = {
	apiKey: process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_API_KEY,
	appId: process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_APP_ID,
	authDomain: process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_AUTH_DOMAIN,
	measurementId:
		process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_MEASUREMENT_ID,
	messagingSenderId:
		process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_MESSAGING_SENDER_ID,
	projectId: process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_PROJECT_ID,
	storageBucket:
		process.env.NEXT_PUBLIC_PRODUCTION_CONFIG_FIREBASE_STORAGE_BUCKET,
};

const stagingConfig = {
	apiKey: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_API_KEY,
	appId: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_APP_ID,
	authDomain: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_AUTH_DOMAIN,
	measurementId: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_MEASUREMENT_ID,
	messagingSenderId:
		process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_MESSAGING_SENDER_ID,
	projectId: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_PROJECT_ID,
	storageBucket: process.env.NEXT_PUBLIC_STAGING_CONFIG_FIREBASE_STORAGE_BUCKET,
};

export const FIREBASE_CONFIG = {
	production: productionConfig,
	staging: stagingConfig,
}[DEPLOYMENT_ENV];
